# IP address to bind to
host_address = "localhost:6096"
# Postgres url to connect to the database with
database_url = "postgres://mogger@localhost/mogger"

[features]
# Allow registering an account
signups = false
# Allow unregistered users to make comments
guest_comments = false

[cookie]
# Require HTTPS for cookies
secure = false
# Domain restriction on cookies
#domain = "site.com"
